version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    container_name: react-app
    stdin_open: true
    volumes:
      - .:/app
