export const GITHUB_ACTION_TYPE = {
  SET_LOADING: 'SET_LOADING',
  CLEAR_USERS: 'CLEAR_USERS',
  GET_USER_DETAIL: 'GET_USER_DETAIL',
  SEARCH_USERS: 'SEARCH_USERS',
  GET_USERS: 'GET_USERS',
  GET_USER_REPOS: 'GET_USER_REPOS',
};

export const ALERT_ACTION_TYPE = {
  SET_ALERT: 'SET_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT',
};
