version: '3.9'

services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    container_name: client
    stdin_open: true
    volumes:
      - .:/app
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: server
    volumes:
      - .:/app
    env_file:
      - ./server/.env
    environment:
      - DB_PROTOCOL=${DB_PROTOCOL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
    ports:
      - '4000:4000'
    restart: always
